// CONFIG block generated by scripts/build-config-block.mjs for "badge"
// Edit project-specific fields marked // TODO before submitting.
// All strings from shadcn-props are pre-escaped via JSON.stringify — safe to use as-is.
// After editing, validate with: npm run check-payload -- <this-file>
const CONFIG = {
  component:  "badge",
  title:      "Badge",
  pageName:   "↳ Badge",
  layout:     "chip",
  docsUrl:    "https://ui.shadcn.com/docs/components/badge",

  // ── Prose from shadcn-props — already correctly escaped, do not retype ─
  summary:    "Compact status / count label.",

  // ── Axes — customize for this component's actual variant/size design ───
  // TODO: adjust variants to match your Figma ComponentSet axes
  variants: ["default","secondary","outline","ghost"],
  // TODO: adjust sizes ([] disables the size axis)
  sizes:    ["sm","default","lg"],

  // ── Token paths — fill in via Step 4.7 get_variable_defs ──────────────
  padH:       { default: 'space/md', sm: 'space/sm', lg: 'space/lg' },      // TODO: replace with your Layout token paths
  radius:     'radius/md',   // TODO: replace with your Layout token path
  labelStyle: { default: 'Label/MD', sm: 'Label/SM', lg: 'Label/LG' }, // TODO: replace with your Typography token names

  // ── Per-variant style — one entry per variant above ────────────────────
  // TODO: replace fill/labelVar/strokeVar with real Theme token paths (Step 4.7)
  style: {
  "default": {
      fill:      null, // TODO: replace with Theme token e.g. 'color/default/default'
      fallback:  "#888888",  // hex fallback when Theme collection absent
      labelVar:  null, // TODO: e.g. 'color/default/content'
      strokeVar: null, // TODO: e.g. 'color/default/border' or null
    },
  "secondary": {
      fill:      null, // TODO: replace with Theme token e.g. 'color/secondary/default'
      fallback:  "#888888",  // hex fallback when Theme collection absent
      labelVar:  null, // TODO: e.g. 'color/secondary/content'
      strokeVar: null, // TODO: e.g. 'color/secondary/border' or null
    },
  "outline": {
      fill:      null, // TODO: replace with Theme token e.g. 'color/outline/default'
      fallback:  "#888888",  // hex fallback when Theme collection absent
      labelVar:  null, // TODO: e.g. 'color/outline/content'
      strokeVar: null, // TODO: e.g. 'color/outline/border' or null
    },
  "ghost": {
      fill:      null, // TODO: replace with Theme token e.g. 'color/ghost/default'
      fallback:  "#888888",  // hex fallback when Theme collection absent
      labelVar:  null, // TODO: e.g. 'color/ghost/content'
      strokeVar: null, // TODO: e.g. 'color/ghost/border' or null
    },
  },

  // ── Label function ─────────────────────────────────────────────────────
  label: (size, variant) => title,

  // ── Icon slots ─────────────────────────────────────────────────────────
  iconSlots: { leading: true, trailing: true, size: 24 },

  // ── Figma element component properties ────────────────────────────────
  componentProps: { label: true, leadingIcon: true, trailingIcon: true },

  // ── Matrix states ─────────────────────────────────────────────────────
  states: [
  { key: "default", group: "default" },
  { key: "hover", group: "default" },
  { key: "pressed", group: "default" },
  { key: "disabled", group: "disabled" },
  ],

  // ── State override applied to matrix instances ─────────────────────────
  applyStateOverride: function applyStateOverride(instance, stateKey, ctx) {
    if (stateKey === "disabled") instance.opacity = 0.38;
  else if (stateKey === "hover") instance.opacity = 0.92;
  else if (stateKey === "pressed") instance.opacity = 0.84;
  else instance.opacity = 1;
  },

  // ── Properties table — rows from shadcn-props (safe JSON strings) ──────
  properties:   [
    ["variant", "enum", "\"default\"", "no", "Visual style."],
    ["asChild", "boolean", "false", "no", "Renders styled classes onto the child via Radix Slot."],
    ["className", "string", "—", "no", "Tailwind class escape hatch."],
  ],

  // ── Usage Do / Don't — customize these bullets ────────────────────────
  usageDo:   [
    "Use badge for its intended semantic purpose.",
    "Keep labels or content concise and actionable.",
    "Follow established spacing and sizing patterns.",
  ],
  usageDont: [
    "Don\'t repurpose badge for unrelated interactions.",
    "Don\'t overload with too much text or too many actions.",
    "Don\'t use outside the design system\'s intended layout grid.",
  ],

  // ── Composes (composite components only) ──────────────────────────────
  // TODO: if this component composes sub-components (CONFIG.layout === '__composes__'), populate here
  composes: [],
};
