// CONFIG block generated by scripts/build-config-block.mjs for "slider"
// Edit project-specific fields marked // TODO before submitting.
// All strings from shadcn-props are pre-escaped via JSON.stringify — safe to use as-is.
// After editing, validate with: npm run check-payload -- <this-file>
const CONFIG = {
  component:  "slider",
  title:      "Slider",
  pageName:   "↳ Slider",
  layout:     "tiny",
  docsUrl:    "https://ui.shadcn.com/docs/components/slider",

  // ── Prose from shadcn-props — already correctly escaped, do not retype ─
  summary:    "Horizontal or vertical range selector.",

  // ── Axes — customize for this component's actual variant/size design ───
  // TODO: adjust variants to match your Figma ComponentSet axes
  variants: ["default"],
  // TODO: adjust sizes ([] disables the size axis)
  sizes:    [],

  // ── Token paths — fill in via Step 4.7 get_variable_defs ──────────────
  padH:       { default: 'space/xs' },      // TODO: replace with your Layout token paths
  radius:     'radius/sm',   // TODO: replace with your Layout token path
  labelStyle: { default: 'Label/SM' }, // TODO: replace with your Typography token names

  // ── Per-variant style — one entry per variant above ────────────────────
  // TODO: replace fill/labelVar/strokeVar with real Theme token paths (Step 4.7)
  style: {
  "default": {
      fill:      null, // TODO: replace with Theme token e.g. 'color/default/default'
      fallback:  "#888888",  // hex fallback when Theme collection absent
      labelVar:  null, // TODO: e.g. 'color/default/content'
      strokeVar: null, // TODO: e.g. 'color/default/border' or null
    },
  },

  // ── Label function ─────────────────────────────────────────────────────
  label: () => null,

  // ── Icon slots ─────────────────────────────────────────────────────────
  iconSlots: { leading: false, trailing: false, size: 24 },

  // ── Figma element component properties ────────────────────────────────
  componentProps: { label: false, leadingIcon: false, trailingIcon: false },

  // ── Matrix states ─────────────────────────────────────────────────────
  states: [
  { key: "default", group: "default" },
  ],

  // ── State override applied to matrix instances ─────────────────────────
  applyStateOverride: function applyStateOverride(instance, stateKey, ctx) {
    // no-op
  },

  // ── Properties table — rows from shadcn-props (safe JSON strings) ──────
  properties:   [
    ["value", "number[]", "—", "no", "Controlled value array (supports multi-thumb)."],
    ["defaultValue", "number[]", "[0]", "no", "Uncontrolled initial value."],
    ["min", "number", "0", "no", "Minimum."],
    ["max", "number", "100", "no", "Maximum."],
    ["step", "number", "1", "no", "Step increment."],
    ["disabled", "boolean", "false", "no", "Disables interaction."],
    ["className", "string", "—", "no", "Tailwind class escape hatch."],
  ],

  // ── Usage Do / Don't — customize these bullets ────────────────────────
  usageDo:   [
    "Use slider for its intended semantic purpose.",
    "Keep labels or content concise and actionable.",
    "Follow established spacing and sizing patterns.",
  ],
  usageDont: [
    "Don\'t repurpose slider for unrelated interactions.",
    "Don\'t overload with too much text or too many actions.",
    "Don\'t use outside the design system\'s intended layout grid.",
  ],

  // ── Composes (composite components only) ──────────────────────────────
  // TODO: if this component composes sub-components (CONFIG.layout === '__composes__'), populate here
  composes: [],
};
